name: Build

on:
  workflow_dispatch:

env:
  NODEJS_VERSION: 22.x

jobs:
  linux-x64:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODEJS_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODEJS_VERSION }}
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Get version from package.json
      run: echo "PKG_VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"
    - name: Package
      run: npm run forge:package
    - name: Zip ASAR
      run: |
        cd out/moyurd-linux-x64
        zip moyurd-asar-linux-x64-${PKG_VERSION}.zip resources/app.asar resources/icon.png
    - name: Generate ASAR checksum
      run: |
        cd out/moyurd-linux-x64
        sha256sum moyurd-asar-linux-x64-${PKG_VERSION}.zip > moyurd-asar-linux-x64-${PKG_VERSION}.zip.sha256
    - name: Zip package
      run: |
        cd out
        zip -r moyurd-pkg-linux-x64-${PKG_VERSION}.zip *
    - name: Generate package checksum
      run: |
        cd out
        sha256sum moyurd-pkg-linux-x64-${PKG_VERSION}.zip > moyurd-pkg-linux-x64-${PKG_VERSION}.zip.sha256
    - name: Upload linux x64 package artifact
      uses: actions/upload-artifact@v4
      with:
        name: pkg-linux-x64-${{ env.PKG_VERSION }}
        path: |
          out/moyurd-pkg-linux-x64-${{ env.PKG_VERSION }}.zip
          out/moyurd-pkg-linux-x64-${{ env.PKG_VERSION }}.zip.sha256
          out/out/moyurd-linux-x64/moyurd-asar-linux-x64-${{ env.PKG_VERSION }}.zip
          out/out/moyurd-linux-x64/moyurd-asar-linux-x64-${{ env.PKG_VERSION }}.zip.sha256
        compression-level: 6
        overwrite: true
    - name: Make
      run: npm run forge:make -- --skip-package
    - name: Generate installer checksum
      run: |
        cd out/make/deb/x64
        sha256sum moyurd_${PKG_VERSION}_amd64.deb > moyurd_${PKG_VERSION}_amd64.deb.sha256
    - name: Upload linux x64 installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer-linux-x64-${{ env.PKG_VERSION }}
        path: |
          out/make/deb/x64/moyurd_${{ env.PKG_VERSION }}_amd64.deb
          out/make/deb/x64/moyurd_${{ env.PKG_VERSION }}_amd64.deb.sha256
        compression-level: 6
        overwrite: true

  windows-x64:
    runs-on: windows-latest
    continue-on-error: false
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODEJS_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODEJS_VERSION }}
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Get version from package.json
      run: echo "PKG_VERSION=$(node -p "require('./package.json').version")" >> $env:GITHUB_ENV
    - name: Package
      run: npm run forge:package
    - name: Zip package
      run: Compress-Archive -Path out/* -DestinationPath "out/moyurd-pkg-windows-x64-${env:PKG_VERSION}.zip"
    - name: Generate package checksum
      run: |
        cd out
        "{0}  {1}" -f (Get-FileHash -Path "moyurd-pkg-windows-x64-${env:PKG_VERSION}.zip" -Algorithm SHA256).Hash, "moyurd-pkg-windows-x64-${env:PKG_VERSION}.zip" > "moyurd-pkg-windows-x64-${env:PKG_VERSION}.zip.sha256"
    - name: Upload windows x64 package artifact
      uses: actions/upload-artifact@v4
      with:
        name: pkg-windows-x64-${{ env.PKG_VERSION }}
        path: |
          out/moyurd-pkg-windows-x64-${{ env.PKG_VERSION }}.zip
          out/moyurd-pkg-windows-x64-${{ env.PKG_VERSION }}.zip.sha256
        compression-level: 6
        overwrite: true
    - name: Make
      run: npm run forge:make -- --skip-package
    - name: Zip windows installer
      run: Compress-Archive -Path out/make/squirrel.windows/x64/* -DestinationPath "out/moyurd-installer-windows-x64-${env:PKG_VERSION}.zip"
    - name: Generate installer checksum
      run: |
        cd out
        "{0}  {1}" -f (Get-FileHash -Path "moyurd-installer-windows-x64-${env:PKG_VERSION}.zip" -Algorithm SHA256).Hash, "moyurd-installer-windows-x64-${env:PKG_VERSION}.zip" > "moyurd-installer-windows-x64-${env:PKG_VERSION}.zip.sha256"
    - name: Upload windows x64 installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer-windows-x64-${{ env.PKG_VERSION }}
        path: |
          out/moyurd-installer-windows-x64-${{ env.PKG_VERSION }}.zip
          out/moyurd-installer-windows-x64-${{ env.PKG_VERSION }}.zip.sha256
        compression-level: 6
        overwrite: true
  release:
    runs-on: ubuntu-latest
    needs: [linux-x64, windows-x64]
    permissions:
      contents: write
    continue-on-error: false
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4
    - name: Get version from package.json
      run: echo "PKG_VERSION=v$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"
    - name: Download artifacts
      uses: actions/download-artifact@v5
      with:
        path: dist
        merge-multiple: true
    - name: Create Release ${{ env.PKG_VERSION }}
      uses: softprops/action-gh-release@v2.3.3
      with:
        tag_name: ${{ env.PKG_VERSION }}
        name: ${{ env.PKG_VERSION }}
        draft: true
        files: dist/**/*
        make_latest: true
